[build]
  command   = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # Fails build when a category is below a threshold
  #[plugins.inputs.thresholds]
    #performance = 0.9
    #accessibility = 0.9
    #best-practices = 0.9
    #seo = 0.9
    #pwa = 0.9

[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
